window.teams = {
  "nba": [
    "atlanta hawks",
    "boston celtics",
    "brooklyn nets",
    "charlotte hornets",
    "chicago bulls",
    "cleveland cavaliers",
    "dallas mavericks",
    "denver nuggets",
    "detroit pistons",
    "golden state warriors",
    "houston rockets",
    "indiana pacers",
    "los angeles clippers",
    "los angeles lakers",
    "memphis grizzlies",
    "miami heat",
    "milwaukee bucks",
    "minnesota timberwolves",
    "new orleans pelicans",
    "new york knicks",
    "oklahoma city thunder",
    "orlando magic",
    "philadelphia sixers",
    "phoenix suns",
    "portland trail blazers",
    "sacramento kings",
    "san antonio spurs",
    "toronto raptors",
    "utah jazz",
    "washington wizards"
  ],
  "mlb": [
    "arizona diamondbacks",
    "atlanta braves",
    "baltimore orioles",
    "boston red sox",
    "chicago cubs",
    "chicago white sox",
    "cincinnati reds",
    "cleveland indians",
    "colorado rockies",
    "detroit tigers",
    "houston astros",
    "kansas city royals",
    "los angeles angels",
    "los angeles dodgers",
    "miami marlins",
    "milwaukee brewers",
    "minnesota twins",
    "new york mets",
    "new york yankees",
    "oakland athletics",
    "philadelphia phillies",
    "pittsburgh pirates",
    "san diego padres",
    "san francisco giants",
    "seattle mariners",
    "st. louis cardinals",
    "tampa bay rays",
    "texas rangers",
    "toronto blue jays",
    "washington nationals"
  ],
  "nfl": [
    "arizona cardinals",
    "atlanta falcons",
    "baltimore ravens",
    "buffalo bills",
    "carolina panthers",
    "chicago bears",
    "cincinnati bengals",
    "cleveland browns",
    "dallas cowboys",
    "denver broncos",
    "detroit lions",
    "green bay packers",
    "houston texans",
    "indianapolis colts",
    "jacksonville jaguars",
    "kansas city chiefs",
    "miami dolphins",
    "minnesota vikings",
    "new england patriots",
    "new orleans saints",
    "new york giants",
    "new york jets",
    "oakland raiders",
    "philadelphia eagles",
    "pittsburgh steelers",
    "san diego chargers",
    "san francisco 49ers",
    "seattle seahawks",
    "los angeles rams",
    "tampa bay buccaneers",
    "tennessee titans",
    "washington redskins"
  ]
}
